In [1]:
# !pip install wordcloud
!c:\Users\amish\AppData\Local\Programs\Python\Python311\python.exe -m pip install wordcloud

Collecting wordcloud
  Downloading wordcloud-1.9.6-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.19.3 in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from wordcloud) (2.0.2)
Requirement already satisfied: pillow in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from wordcloud) (11.3.0)
Requirement already satisfied: matplotlib in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from wordcloud) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)
Downloading wordcloud-1.9.6-cp311-cp311-win_amd64.whl (306 kB)
Installing collected packages: wordcloud
Successfully installed wordcloud-1.9.6

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
# Importing necessary libraries
import numpy as np        # For numerical operations
import pandas as pd       # For data manipulation and analysis
import matplotlib.pyplot as plt  # For data visualization
%matplotlib inline

# Importing WordCloud for text visualization
from wordcloud import WordCloud

# Importing NLTK for natural language processing
import nltk
from nltk.corpus import stopwords    # For stopwords


# Downloading NLTK data
nltk.download('stopwords')   # Downloading stopwords data
nltk.download('punkt')       # Downloading tokenizer data

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\amish\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\amish\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [50]:
# Read the CSV file
df = pd.read_csv('spam.csv')

# Display the first few rows of the DataFrame
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [51]:
df.drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace = True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [52]:
# Rename the columns name
df.rename(columns = {'v1': 'target', 'v2': 'text'}, inplace = True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [53]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])

df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [54]:
#check duplicate values
df.duplicated().sum()

np.int64(403)

In [55]:

len(df)

5572

In [56]:
#remove Duplicate
df = df.drop_duplicates(keep = 'first')
len(df)

5169

In [57]:
# Importing the Porter Stemmer for text stemming
from nltk.stem.porter import PorterStemmer

# Importing the string module for handling special characters
import string

# Creating an instance of the Porter Stemmer
ps = PorterStemmer()

In [58]:
# Lowercase transformation and text preprocessing function
def transform_text(text):
    # Transform the text to lowercase
    text = text.lower()
    
    # Tokenization using NLTK
    text = nltk.word_tokenize(text)
    
    # Removing special characters
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
            
    # Removing stop words and punctuation
    text = y[:]
    y.clear()
    
    # Loop through the tokens and remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
        
    # Stemming using Porter Stemmer
    text = y[:]
    y.clear()
    for i in text:
        y.append(ps.stem(i))
    
    # Join the processed tokens back into a single string
    return " ".join(y)

In [59]:
import nltk
nltk.download('punkt')

nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\amish\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\amish\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [60]:
# nltk.data.path.append("C:/Users/amish/AppData/Roaming/nltk_data")
# import nltk
# nltk.download('punkt', download_dir='C:/Users/amish/nltk_data')
# nltk.data.path.append('C:/Users/amish/nltk_data')

In [61]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
tfid = TfidfVectorizer(max_features = 500)

In [63]:
import nltk
nltk.download('punkt', download_dir='C:/Users/amish/nltk_data')
nltk.data.path.append('C:/Users/amish/nltk_data')

[nltk_data] Downloading package punkt to C:/Users/amish/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [64]:
import re
import nltk

def transform_text(text):
    text = text.lower()
    try:
        tokens = nltk.word_tokenize(text)
    except LookupError:
        # fallback regex tokenizer
        tokens = re.findall(r'\b\w+\b', text)
    # Remove special characters
    y = [i for i in tokens if i.isalnum()]
    return y

In [65]:
df['transformed_text'] = df['text'].apply(transform_text)
df.head()

,target,text,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...","[go, until, jurong, point, crazy, available, o..."
1,0,Ok lar... Joking wif u oni...,"[ok, lar, joking, wif, u, oni]"
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,"[free, entry, in, 2, a, wkly, comp, to, win, f..."
3,0,U dun say so early hor... U c already then say...,"[u, dun, say, so, early, hor, u, c, already, t..."
4,0,"Nah I don't think he goes to usf, he lives aro...","[nah, i, don, t, think, he, goes, to, usf, he,..."

In [66]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
tfid = TfidfVectorizer(max_features = 500)

In [71]:
# convert list to string
df['transformed_text'] = df['transformed_text'].apply(lambda x: " ".join(x))

# vectorization
X = tfid.fit_transform(df['transformed_text'])
y = df['target'].values

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(X,y,test_size = 0.20, random_state = 2)

In [86]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [85]:
!c:\Users\amish\AppData\Local\Programs\Python\Python311\python.exe -m pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (2.0.2)
Requirement already satisfied: scipy in c:\users\amish\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (1.14.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 985.5 kB/s eta 0:01:43
   ---------------------------------------- 0.8/101.7 MB 1.0 MB/s eta 0:01:37
   ---------------------------------------- 1.0/101.7 MB 1.0 MB/s eta 0:01:36
    --------------------------------------- 1.3/101.7 MB 1.0 MB/s eta 0:01:36
    --------------------------------------- 1.6/101.7 MB 1.0 MB/s eta 0:01:38
    --------------------------------------- 1.8/101.7 MB 1.0 MB/s eta 0:01:36
    --------------------------------------- 2.1/101.7 MB 1.1 MB/s eta 0:01:32
    --------------------------------------- 2.4/101.7 MB 1.2 MB/s eta 0:01:26
   - -------------------------------------- 2.9/101.7 MB 1.2 MB/s eta 0:01:21
   - -------------------------------------- 3.1/101.7 MB 1.3 MB/s eta 0:01:18
   - -------------------------------------- 3.4/101.7 MB 1.3 MB/s eta 0:01:17
   - -------------------------------------- 3.7/101.7 MB 1.3 MB/s eta 0:01:18
   - -------------------------------------- 3.9/101.7 MB 1.3 MB/s eta 0:01:18
   - -------------------------------------- 4.5/101.7 MB 1.3 MB/s eta 0:01:14
   - -------------------------------------- 4.7/101.7 MB 1.3 MB/s eta 0:01:14
   -- ------------------------------------- 5.2/101.7 MB 1.4 MB/s eta 0:01:11
   -- ------------------------------------- 5.5/101.7 MB 1.4 MB/s eta 0:01:10
   -- ------------------------------------- 5.8/101.7 MB 1.4 MB/s eta 0:01:10
   -- ------------------------------------- 5.8/101.7 MB 1.4 MB/s eta 0:01:10
   -- ------------------------------------- 6.0/101.7 MB 1.3 MB/s eta 0:01:13
   -- ------------------------------------- 6.0/101.7 MB 1.3 MB/s eta 0:01:13
   -- ------------------------------------- 6.3/101.7 MB 1.2 MB/s eta 0:01:18
   -- ------------------------------------- 6.3/101.7 MB 1.2 MB/s eta 0:01:18
   -- ------------------------------------- 6.3/101.7 MB 1.2 MB/s eta 0:01:18
   -- ------------------------------------- 6.6/101.7 MB 1.1 MB/s eta 0:01:24
   -- ------------------------------------- 6.6/101.7 MB 1.1 MB/s eta 0:01:24
   -- ------------------------------------- 6.8/101.7 MB 1.1 MB/s eta 0:01:25
   -- ------------------------------------- 7.3/101.7 MB 1.1 MB/s eta 0:01:24
   -- ------------------------------------- 7.3/101.7 MB 1.1 MB/s eta 0:01:24
   -- ------------------------------------- 7.6/101.7 MB 1.1 MB/s eta 0:01:25
   --- ------------------------------------ 7.9/101.7 MB 1.1 MB/s eta 0:01:24
   --- ------------------------------------ 8.4/101.7 MB 1.1 MB/s eta 0:01:22
   --- ------------------------------------ 8.7/101.7 MB 1.2 MB/s eta 0:01:21
   --- ------------------------------------ 8.9/101.7 MB 1.2 MB/s eta 0:01:19
   --- ------------------------------------ 9.2/101.7 MB 1.2 MB/s eta 0:01:19
   --- ------------------------------------ 9.4/101.7 MB 1.2 MB/s eta 0:01:20
   --- ------------------------------------ 9.7/101.7 MB 1.2 MB/s eta 0:01:20
   --- ------------------------------------ 10.0/101.7 MB 1.2 MB/s eta 0:01:19
   ---- ----------------------------------- 10.2/101.7 MB 1.2 MB/s eta 0:01:18
   ---- ----------------------------------- 10.5/101.7 MB 1.2 MB/s eta 0:01:19
   ---- ----------------------------------- 10.5/101.7 MB 1.2 MB/s eta 0:01:19
   ---- ----------------------------------- 10.7/101.7 MB 1.1 MB/s eta 0:01:20
   ---- ----------------------------------- 11.0/101.7 MB 1.2 MB/s eta 0:01:19
   ---- ----------------------------------- 11.0/101.7 MB 1.2 MB/s eta 0:01:19
   ---- ----------------------------------- 11.0/101.7 MB 1.2 MB/s eta 0:01:19
   ---- ----------------------------------- 11.3/101.7 MB 1.1 MB/s eta 0:01:22
   ---- ----------------------------------- 11.5/101.7 MB 1.1 MB/s eta 0:01:21
   ---- ----------------------------------- 11.5/101.7 MB 1.1 MB/s eta 0:01:21
   ---- ----------------------------------- 11.8/101.7 MB 1.1 MB/s eta 0:01:23
   ---- ----------------------------------- 12.1/101.7 MB 1.1 MB/s eta 0:01:22
   ---- ----------------------------------- 12.3/101.7 MB 1.1 MB/s eta 0:01:24
   ---- ----------------------------------- 12.3/101.7 MB 1.1 MB/s eta 0:01:24
   ---- ----------------------------------- 12.6/101.7 MB 1.1 MB/s eta 0:01:24
   ---- ----------------------------------- 12.6/101.7 MB 1.1 MB/s eta 0:01:24
   ----- ---------------------------------- 13.1/101.7 MB 1.1 MB/s eta 0:01:23
   ----- ---------------------------------- 13.4/101.7 MB 1.1 MB/s eta 0:01:23
   ----- ---------------------------------- 13.4/101.7 MB 1.1 MB/s eta 0:01:23
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:23
   ----- ---------------------------------- 13.9/101.7 MB 1.1 MB/s eta 0:01:23
   ----- ---------------------------------- 14.2/101.7 MB 1.1 MB/s eta 0:01:22
   ----- ---------------------------------- 14.4/101.7 MB 1.1 MB/s eta 0:01:22
   ----- ---------------------------------- 14.7/101.7 MB 1.1 MB/s eta 0:01:22
   ----- ---------------------------------- 14.9/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 15.2/101.7 MB 1.1 MB/s eta 0:01:21
   ------ --------------------------------- 15.5/101.7 MB 1.1 MB/s eta 0:01:21
   ------ --------------------------------- 15.7/101.7 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 15.7/101.7 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 16.0/101.7 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 16.3/101.7 MB 1.1 MB/s eta 0:01:21
   ------ --------------------------------- 16.5/101.7 MB 1.1 MB/s eta 0:01:21
   ------ --------------------------------- 16.8/101.7 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 17.0/101.7 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 17.3/101.7 MB 1.1 MB/s eta 0:01:19
   ------ --------------------------------- 17.3/101.7 MB 1.1 MB/s eta 0:01:19
   ------ --------------------------------- 17.3/101.7 MB 1.1 MB/s eta 0:01:19
   ------ --------------------------------- 17.6/101.7 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 17.6/101.7 MB 1.1 MB/s eta 0:01:20
   ------- -------------------------------- 17.8/101.7 MB 1.0 MB/s eta 0:01:21
   ------- -------------------------------- 17.8/101.7 MB 1.0 MB/s eta 0:01:21
   ------- -------------------------------- 18.1/101.7 MB 1.0 MB/s eta 0:01:22
   ------- -------------------------------- 18.1/101.7 MB 1.0 MB/s eta 0:01:22
   ------- -------------------------------- 18.4/101.7 MB 1.0 MB/s eta 0:01:22
   ------- -------------------------------- 18.6/101.7 MB 1.0 MB/s eta 0:01:22
   ------- -------------------------------- 18.9/101.7 MB 1.0 MB/s eta 0:01:22
   ------- -------------------------------- 19.1/101.7 MB 1.0 MB/s eta 0:01:21
   ------- -------------------------------- 19.4/101.7 MB 1.0 MB/s eta 0:01:21
   ------- -------------------------------- 19.4/101.7 MB 1.0 MB/s eta 0:01:21
   ------- -------------------------------- 19.9/101.7 MB 1.0 MB/s eta 0:01:20
   -------- ------------------------------- 20.4/101.7 MB 1.0 MB/s eta 0:01:18
   -------- ------------------------------- 20.4/101.7 MB 1.0 MB/s eta 0:01:18
   -------- ------------------------------- 20.7/101.7 MB 1.0 MB/s eta 0:01:19
   -------- ------------------------------- 20.7/101.7 MB 1.0 MB/s eta 0:01:19
   -------- ------------------------------- 20.7/101.7 MB 1.0 MB/s eta 0:01:19
   -------- ------------------------------- 21.0/101.7 MB 1.0 MB/s eta 0:01:20
   -------- ------------------------------- 21.0/101.7 MB 1.0 MB/s eta 0:01:20
   -------- ------------------------------- 21.2/101.7 MB 1.0 MB/s eta 0:01:20
   -------- ------------------------------- 21.2/101.7 MB 1.0 MB/s eta 0:01:20
   -------- ------------------------------ 21.5/101.7 MB 999.2 kB/s eta 0:01:21
   -------- ------------------------------ 21.5/101.7 MB 999.2 kB/s eta 0:01:21
   -------- ------------------------------ 21.8/101.7 MB 991.1 kB/s eta 0:01:21
   -------- ------------------------------ 21.8/101.7 MB 991.1 kB/s eta 0:01:21
   -------- ------------------------------ 22.0/101.7 MB 985.5 kB/s eta 0:01:21
   -------- ------------------------------ 22.0/101.7 MB 985.5 kB/s eta 0:01:21
   -------- ------------------------------ 22.0/101.7 MB 985.5 kB/s eta 0:01:21
   -------- ------------------------------ 22.3/101.7 MB 971.9 kB/s eta 0:01:22
   -------- ------------------------------ 22.3/101.7 MB 971.9 kB/s eta 0:01:22
   -------- ------------------------------ 22.5/101.7 MB 958.4 kB/s eta 0:01:23
   -------- ------------------------------ 22.5/101.7 MB 958.4 kB/s eta 0:01:23
   -------- ------------------------------ 22.8/101.7 MB 952.4 kB/s eta 0:01:23
   -------- ------------------------------ 22.8/101.7 MB 952.4 kB/s eta 0:01:23
   -------- ------------------------------ 22.8/101.7 MB 952.4 kB/s eta 0:01:23
   -------- ------------------------------ 23.1/101.7 MB 936.2 kB/s eta 0:01:24
   -------- ------------------------------ 23.1/101.7 MB 936.2 kB/s eta 0:01:24
   -------- ------------------------------ 23.3/101.7 MB 934.4 kB/s eta 0:01:24
   --------- ----------------------------- 23.6/101.7 MB 936.2 kB/s eta 0:01:24
   --------- ----------------------------- 23.9/101.7 MB 941.3 kB/s eta 0:01:23
   --------- ----------------------------- 24.1/101.7 MB 942.4 kB/s eta 0:01:23
   --------- ----------------------------- 24.4/101.7 MB 944.0 kB/s eta 0:01:22
   --------- ----------------------------- 24.4/101.7 MB 944.0 kB/s eta 0:01:22
   --------- ----------------------------- 24.4/101.7 MB 944.0 kB/s eta 0:01:22
   --------- ----------------------------- 24.4/101.7 MB 944.0 kB/s eta 0:01:22
   --------- ----------------------------- 24.4/101.7 MB 944.0 kB/s eta 0:01:22
   --------- ----------------------------- 24.4/101.7 MB 944.0 kB/s eta 0:01:22
   --------- ----------------------------- 24.4/101.7 MB 944.0 kB/s eta 0:01:22
   --------- ----------------------------- 24.4/101.7 MB 944.0 kB/s eta 0:01:22
   --------- ----------------------------- 24.4/101.7 MB 944.0 kB/s eta 0:01:22
   --------- ----------------------------- 24.6/101.7 MB 884.0 kB/s eta 0:01:28
   --------- ----------------------------- 24.9/101.7 MB 889.0 kB/s eta 0:01:27
   --------- ----------------------------- 24.9/101.7 MB 889.0 kB/s eta 0:01:27
   --------- ----------------------------- 25.2/101.7 MB 885.5 kB/s eta 0:01:27
   --------- ----------------------------- 25.2/101.7 MB 885.5 kB/s eta 0:01:27
   --------- ----------------------------- 25.2/101.7 MB 885.5 kB/s eta 0:01:27
   --------- ----------------------------- 25.4/101.7 MB 872.0 kB/s eta 0:01:28
   --------- ----------------------------- 25.4/101.7 MB 872.0 kB/s eta 0:01:28
   --------- ----------------------------- 25.4/101.7 MB 872.0 kB/s eta 0:01:28
   --------- ----------------------------- 25.4/101.7 MB 872.0 kB/s eta 0:01:28
   --------- ----------------------------- 25.7/101.7 MB 857.9 kB/s eta 0:01:29
   --------- ----------------------------- 25.7/101.7 MB 857.9 kB/s eta 0:01:29
   --------- ----------------------------- 25.7/101.7 MB 857.9 kB/s eta 0:01:29
   --------- ----------------------------- 26.0/101.7 MB 842.4 kB/s eta 0:01:30
   --------- ----------------------------- 26.0/101.7 MB 842.4 kB/s eta 0:01:30
   --------- ----------------------------- 26.0/101.7 MB 842.4 kB/s eta 0:01:30
   ---------- ---------------------------- 26.2/101.7 MB 831.4 kB/s eta 0:01:31
   ---------- ---------------------------- 26.2/101.7 MB 831.4 kB/s eta 0:01:31
   ---------- ---------------------------- 26.2/101.7 MB 831.4 kB/s eta 0:01:31
   ---------- ---------------------------- 26.2/101.7 MB 831.4 kB/s eta 0:01:31
   ---------- ---------------------------- 26.2/101.7 MB 831.4 kB/s eta 0:01:31
   ---------- ---------------------------- 26.5/101.7 MB 787.2 kB/s eta 0:01:36
   ---------- ---------------------------- 26.5/101.7 MB 787.2 kB/s eta 0:01:36
   ---------- ---------------------------- 26.5/101.7 MB 787.2 kB/s eta 0:01:36
   ---------- ---------------------------- 26.5/101.7 MB 787.2 kB/s eta 0:01:36
   ---------- ---------------------------- 26.5/101.7 MB 787.2 kB/s eta 0:01:36
   ---------- ---------------------------- 26.5/101.7 MB 787.2 kB/s eta 0:01:36
   ---------- ---------------------------- 27.0/101.7 MB 736.3 kB/s eta 0:01:42
   ---------- ---------------------------- 27.0/101.7 MB 736.3 kB/s eta 0:01:42
   ---------- ---------------------------- 27.0/101.7 MB 736.3 kB/s eta 0:01:42
   ---------- ---------------------------- 27.3/101.7 MB 716.9 kB/s eta 0:01:44
   ---------- ---------------------------- 27.3/101.7 MB 716.9 kB/s eta 0:01:44
   ---------- ---------------------------- 27.3/101.7 MB 716.9 kB/s eta 0:01:44
   ---------- ---------------------------- 27.5/101.7 MB 712.6 kB/s eta 0:01:45
   ---------- ---------------------------- 27.5/101.7 MB 712.6 kB/s eta 0:01:45
   ---------- ---------------------------- 27.5/101.7 MB 712.6 kB/s eta 0:01:45
   ---------- ---------------------------- 27.5/101.7 MB 712.6 kB/s eta 0:01:45
   ---------- ---------------------------- 27.8/101.7 MB 707.8 kB/s eta 0:01:45
   ---------- ---------------------------- 27.8/101.7 MB 707.8 kB/s eta 0:01:45
   ---------- ---------------------------- 27.8/101.7 MB 707.8 kB/s eta 0:01:45
   ---------- ---------------------------- 27.8/101.7 MB 707.8 kB/s eta 0:01:45
   ---------- ---------------------------- 28.0/101.7 MB 687.6 kB/s eta 0:01:48
   ---------- ---------------------------- 28.0/101.7 MB 687.6 kB/s eta 0:01:48
   ---------- ---------------------------- 28.0/101.7 MB 687.6 kB/s eta 0:01:48
   ---------- ---------------------------- 28.0/101.7 MB 687.6 kB/s eta 0:01:48
   ---------- ---------------------------- 28.3/101.7 MB 657.1 kB/s eta 0:01:52
   ---------- ---------------------------- 28.3/101.7 MB 657.1 kB/s eta 0:01:52
   ---------- ---------------------------- 28.3/101.7 MB 657.1 kB/s eta 0:01:52
   ---------- ---------------------------- 28.6/101.7 MB 633.4 kB/s eta 0:01:56
   ---------- ---------------------------- 28.6/101.7 MB 633.4 kB/s eta 0:01:56
   ---------- ---------------------------- 28.6/101.7 MB 633.4 kB/s eta 0:01:56
   ----------- --------------------------- 28.8/101.7 MB 616.2 kB/s eta 0:01:59
   ----------- --------------------------- 28.8/101.7 MB 616.2 kB/s eta 0:01:59
   ----------- --------------------------- 28.8/101.7 MB 616.2 kB/s eta 0:01:59
   ----------- --------------------------- 28.8/101.7 MB 616.2 kB/s eta 0:01:59
   ----------- --------------------------- 28.8/101.7 MB 616.2 kB/s eta 0:01:59
   ----------- --------------------------- 29.1/101.7 MB 601.1 kB/s eta 0:02:01
   ----------- --------------------------- 29.1/101.7 MB 601.1 kB/s eta 0:02:01
   ----------- --------------------------- 29.1/101.7 MB 601.1 kB/s eta 0:02:01
   ----------- --------------------------- 29.4/101.7 MB 591.0 kB/s eta 0:02:03
   ----------- --------------------------- 29.4/101.7 MB 591.0 kB/s eta 0:02:03
   ----------- --------------------------- 29.4/101.7 MB 591.0 kB/s eta 0:02:03
   ----------- --------------------------- 29.6/101.7 MB 582.2 kB/s eta 0:02:04
   ----------- --------------------------- 29.6/101.7 MB 582.2 kB/s eta 0:02:04
   ----------- --------------------------- 29.6/101.7 MB 582.2 kB/s eta 0:02:04
   ----------- --------------------------- 29.9/101.7 MB 576.7 kB/s eta 0:02:05
   ----------- --------------------------- 30.1/101.7 MB 578.8 kB/s eta 0:02:04
   ----------- --------------------------- 30.4/101.7 MB 577.6 kB/s eta 0:02:04
   ----------- --------------------------- 30.7/101.7 MB 577.3 kB/s eta 0:02:04
   ----------- --------------------------- 30.9/101.7 MB 578.8 kB/s eta 0:02:03
   ----------- --------------------------- 31.2/101.7 MB 579.4 kB/s eta 0:02:02
   ----------- --------------------------- 31.2/101.7 MB 579.4 kB/s eta 0:02:02
   ------------ -------------------------- 31.5/101.7 MB 573.3 kB/s eta 0:02:03
   ------------ -------------------------- 31.7/101.7 MB 577.6 kB/s eta 0:02:02
   ------------ -------------------------- 32.0/101.7 MB 572.1 kB/s eta 0:02:02
   ------------ -------------------------- 32.2/101.7 MB 577.6 kB/s eta 0:02:01
   ------------ -------------------------- 32.5/101.7 MB 578.2 kB/s eta 0:02:00
   ------------ -------------------------- 33.0/101.7 MB 579.1 kB/s eta 0:01:59
   ------------ -------------------------- 33.3/101.7 MB 581.0 kB/s eta 0:01:58
   ------------ -------------------------- 33.6/101.7 MB 583.7 kB/s eta 0:01:57
   ------------ -------------------------- 33.6/101.7 MB 583.7 kB/s eta 0:01:57
   ------------ -------------------------- 33.8/101.7 MB 580.7 kB/s eta 0:01:57
   ------------ -------------------------- 33.8/101.7 MB 580.7 kB/s eta 0:01:57
   ------------- ------------------------- 34.1/101.7 MB 572.2 kB/s eta 0:01:59
   ------------- ------------------------- 34.1/101.7 MB 572.2 kB/s eta 0:01:59
   ------------- ------------------------- 34.3/101.7 MB 568.4 kB/s eta 0:01:59
   ------------- ------------------------- 34.3/101.7 MB 568.4 kB/s eta 0:01:59
   ------------- ------------------------- 34.6/101.7 MB 570.0 kB/s eta 0:01:58
   ------------- ------------------------- 34.9/101.7 MB 574.3 kB/s eta 0:01:57
   ------------- ------------------------- 34.9/101.7 MB 574.3 kB/s eta 0:01:57
   ------------- ------------------------- 35.1/101.7 MB 577.9 kB/s eta 0:01:56
   ------------- ------------------------- 35.4/101.7 MB 580.3 kB/s eta 0:01:55
   ------------- ------------------------- 35.4/101.7 MB 580.3 kB/s eta 0:01:55
   ------------- ------------------------- 35.7/101.7 MB 579.7 kB/s eta 0:01:54
   ------------- ------------------------- 35.7/101.7 MB 579.7 kB/s eta 0:01:54
   ------------- ------------------------- 35.9/101.7 MB 572.4 kB/s eta 0:01:55
   ------------- ------------------------- 36.2/101.7 MB 577.9 kB/s eta 0:01:54
   ------------- ------------------------- 36.4/101.7 MB 577.0 kB/s eta 0:01:54
   -------------- ------------------------ 36.7/101.7 MB 577.3 kB/s eta 0:01:53
   -------------- ------------------------ 37.2/101.7 MB 578.2 kB/s eta 0:01:52
   -------------- ------------------------ 37.5/101.7 MB 577.6 kB/s eta 0:01:52
   -------------- ------------------------ 37.5/101.7 MB 577.6 kB/s eta 0:01:52
   -------------- ------------------------ 37.7/101.7 MB 570.7 kB/s eta 0:01:53
   -------------- ------------------------ 37.7/101.7 MB 570.7 kB/s eta 0:01:53
   -------------- ------------------------ 38.0/101.7 MB 572.4 kB/s eta 0:01:52
   -------------- ------------------------ 38.0/101.7 MB 572.4 kB/s eta 0:01:52
   -------------- ------------------------ 38.3/101.7 MB 576.1 kB/s eta 0:01:51
   -------------- ------------------------ 38.3/101.7 MB 576.1 kB/s eta 0:01:51
   -------------- ------------------------ 38.5/101.7 MB 576.4 kB/s eta 0:01:50
   -------------- ------------------------ 38.5/101.7 MB 576.4 kB/s eta 0:01:50
   -------------- ------------------------ 38.8/101.7 MB 574.6 kB/s eta 0:01:50
   -------------- ------------------------ 38.8/101.7 MB 574.6 kB/s eta 0:01:50
   -------------- ------------------------ 38.8/101.7 MB 574.6 kB/s eta 0:01:50
   -------------- ------------------------ 38.8/101.7 MB 574.6 kB/s eta 0:01:50
   -------------- ------------------------ 39.1/101.7 MB 568.0 kB/s eta 0:01:51

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [83]:
from xgboost import XGBClassifier

ModuleNotFoundError: No module named 'xgboost'

In [84]:
!python --version

Python 3.11.9

In [87]:
svc = SVC(kernel= "sigmoid", gamma  = 1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth = 5)
lrc = LogisticRegression(solver = 'liblinear', penalty = 'l1')
rfc = RandomForestClassifier(n_estimators = 50, random_state = 2 )
abc = AdaBoostClassifier(n_estimators = 50, random_state = 2)
bc = BaggingClassifier(n_estimators = 50, random_state = 2)
etc = ExtraTreesClassifier(n_estimators = 50, random_state = 2)
gbdt = GradientBoostingClassifier(n_estimators = 50, random_state = 2)    
xgb  = XGBClassifier(n_estimators = 50, random_state = 2)

In [88]:
clfs = {
    'SVC': svc,
    'KNN': knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'Adaboost': abc,
    'Bgc': bc,
    'ETC': etc,
    'GBDT': gbdt,
    'xgb': xgb
    
}

In [89]:
from sklearn.metrics import accuracy_score, precision_score
def train_classifier(clfs, X_train, y_train, X_test, y_test):
    clfs.fit(X_train,y_train)
    y_pred = clfs.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    return accuracy , precision

In [90]:
accuracy_scores = []
precision_scores = []
for name , clfs in clfs.items():
    current_accuracy, current_precision = train_classifier(clfs, X_train, y_train, X_test, y_test)
    print()
    print("For: ", name)
    print("Accuracy: ", current_accuracy)
    print("Precision: ", current_precision)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For:  SVC
Accuracy:  0.971953578336557
Precision:  0.9504132231404959

For:  KNN
Accuracy:  0.925531914893617
Precision:  0.9841269841269841

For:  NB
Accuracy:  0.971953578336557
Precision:  0.9658119658119658

For:  DT
Accuracy:  0.9448742746615088
Precision:  0.8584070796460177

For:  LR
Accuracy:  0.9709864603481625
Precision:  0.9426229508196722

For:  RF
Accuracy:  0.9777562862669246
Precision:  0.9831932773109243

For:  Adaboost
Accuracy:  0.9400386847195358
Precision:  0.9130434782608695

For:  Bgc
Accuracy:  0.965183752417795
Precision:  0.875

For:  ETC
Accuracy:  0.9758220502901354
Precision:  0.959349593495935

For:  GBDT
Accuracy:  0.960348162475822
Precision:  0.9619047619047619

For:  xgb
Accuracy:  0.9806576402321083
Precision:  0.9836065573770492